apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: churn-model
spec:
  predictor:
    serviceAccountName: s3-sa
    sklearn:
      storageUri: s3://mlops-s3-cicd-bucket/models/churn_model_f54f537b5a0f3161909d72d8c0eade639d12e0a7.pkl