apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: churn-model
spec:
  predictor:
    serviceAccountName: s3-sa
    sklearn:
      storageUri: s3://mlops-s3-cicd-bucket/models/churn_model_dbb8aa73e3f6521cd4cdfb4123e22088e8505f20.pkl